spring:
  profiles:
    active: local # default
    group:
      local:
        - common
      prod:
        - common

---
# 공통으로 설정할 값들
spring:
  config:
    activate:
      on-profile: common

kakao:
  rest:
    api:
      key: ${KAKAO_REST_API_KEY}

---
# local에서 사용
spring:
  config:
    activate:
      on-profile: local
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/proj7
#    username: root
#    password: testporj7
#  redis:
#    host: localhost
#    port: 6379
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true

---
# prod에서 사용
spring:
  config:
    activate:
      on-profile: prod
