#spring.application.name=restful-service

server:
  port: 8088

logging:
  level:
    org.springframework: debug

spring:
  message:
    basename: messages
#  security:
#    user:
#      name: username
#      password: userpw

management:
  endpoints:
    web:
      exposure:
        include: "*"